name: Validate 'setup-singularity'

on:
  push:
    branches:
      - master
    
jobs:
  run-sim:
    name: Run singularity
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Singularity 
        uses: eWaterCycle/setup-singularity@v5
        with:
          singularity-version: 3.6.4
      - name: run a simulation
        run: | 
          singularity run -B `pwd`/archives:/root/in -B `pwd`:/root/out docker://ghcr.io/biosimulators/biosimulators_vcell/vcell -i '/root/in/CombineArchiveHasSedDocumentsInNestedDirectories.omex' -o /root/out
          ls

