name: Validate 'setup-singularity'

on:
  push:
    branches:
      - master
    
jobs:
  run-sim:
    name: Run singularity
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Singularity 
        uses: eWaterCycle/setup-singularity@v5
        with:
          singularity-version: 3.6.4
      - name: Build a singularity container
        run: singularity build vcell.img docker://ghcr.io/biosimulators/biosimulators_vcell/vcell

      - name: Run a singularity   
        run: |
          ls
          singularity run vcell.img -v
